all: count-comparisons-first-pivo-quick-sort count-comparisons-last-pivo-quick-sort count-comparisons-median-of-three-pivo-quick-sort

count-comparisons-first-pivo-quick-sort: count-comparisons-first-pivo-quick-sort.o
	gcc -Wall count-comparisons-first-pivo-quick-sort.c -o count-comparisons-first-pivo-quick-sort

count-comparisons-last-pivo-quick-sort: count-comparisons-last-pivo-quick-sort.o
	gcc -Wall count-comparisons-last-pivo-quick-sort.c -o count-comparisons-last-pivo-quick-sort

count-comparisons-median-of-three-pivo-quick-sort: count-comparisons-median-of-three-pivo-quick-sort.o
	gcc -Wall count-comparisons-median-of-three-pivo-quick-sort.c -o count-comparisons-median-of-three-pivo-quick-sort

clean:
	rm -rf *o count-comparisons-first-pivo-quick-sort count-comparisons-last-pivo-quick-sort count-comparisons-median-of-three-pivo-quick-sort
