all: counting-inversions-brute-force counting-inversions-divide-conquer

counting-inversions-brute-force: counting-inversions-brute-force.o
	gcc -Wall counting-inversions-brute-force.o -o counting-inversions-brute-force

counting-inversions-divide-conquer: counting-inversions-divide-conquer.o
	gcc -Wall counting-inversions-divide-conquer.o -o counting-inversions-divide-conquer

clean:
	rm -rf *o counting-inversions-brute-force counting-inversions-divide-conquer
